/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.lkrtz.lane.compiler;

import org.antlr.runtime.ANTLRInputStream;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws Exception {
        System.out.println(new App().getGreeting());
        App.class.getResourceAsStream(null);
        ANTLRInputStream input = new ANTLRInputStream(System.in);
        
    }
}
